### PR TITLE
Review stream csv 1

### PR DESCRIPTION
**Pull request by baallan**
see if this works

### CODE REVIEW

**Comment by oceandlr** [comment]
@baallan 00fb3068 touches ldmsd.c -- please put that in as a separate pull request on OVIS-4.

**Comment by oceandlr** [comment]
@baallan 65e9073 I will take, but also hello_cat_publisher -> ldmsd_stream_publish in the deprecation, so you will want to put your change there.

**Comment by oceandlr** [comment]
@baallan Thank you for the fixes in 3469953.
A few questions:
1) not sure about 712 & 738. Rarely does anyone want this level of debugging. But I will take them, rather than having commented out code in the src.
2) 1246 & 1249 look wrong. 
    if (stream_idx || cfgstate != CFG_PRE) {
    else {
       stream_idx = idx_create();
       ...
    }

The check is a problem. 
* if there is no stream_idx, you should not go into the rest of it, the cfg_state will be wrong.
* the stream_idx is created in csv_stream_store_init and recreated if the config fails.  The way it is now is entirely consistent with store_csv. The lack of consistency across code make things more difficult to ensure functionality, to test, and to serve as a model for others.

3) I disagree with changing the rolltype in 1360. If they've put in something wrong, then it shouldn't work. We shouldn't assume a fix for their error.

**Comment by baallan** [comment]
@oceandlr I put this PR up for you to see what was going on and discuss, not because it was completely ready. in particular there are still locking issues which the mods here haven't completely resolved. will leave more focused replies to you notes where I can.

**Comment by baallan** [comment]
>     1. not sure about 712 & 738. Rarely does anyone want this level of debugging. But I will take them, rather than having commented out code in the src.

This is something we can delete or encapsulate in #ifdef  STREAM_CSV_DEBUG; I would lean toward the latter and perhaps use such a macro in several places.
> 
>     2. 1246 & 1249 look wrong.
>        if (stream_idx || cfgstate != CFG_PRE) {
>        else {
>        stream_idx = idx_create();
>        ...
>        }
> 
> 
> The check is a problem.
> 
>     * if there is no stream_idx, you should not go into the rest of it, the cfg_state will be wrong.
> 
>     * the stream_idx is created in csv_stream_store_init and recreated if the config fails.  The way it is now is entirely consistent with store_csv. The lack of consistency across code make things more difficult to ensure functionality, to test, and to serve as a model for others.

Store_csv is simpler (it isn't managing stream subscriptions); This part of my suggested changes isn't fully baked yet -- it appears we maybe cannot close a stream subscription without a deadlock.

> 
>     1. I disagree with changing the rolltype in 1360. If they've put in something wrong, then it shouldn't work. We shouldn't assume a fix for their error.

There's no change to rolltype here. there is just the enforcement of the minimum rollover interval, which is done similarly in store_csv; the new thing here is just warning about it instead of doing it silently.

**Comment by oceandlr** [comment]
Re @baallan above
1) perhaps a verbose macro in the code is fine. I could see that multiple types of debugging could be unweildly. Do we do that anywhere else?
2) there is no stream unsubscribe. So it is the same as store_csv in that way.
3) ok about the warning. I was mislead by the the "round up" in the comment

**Comment by baallan** [comment]
@oceandlr an odd thing I'm still debugging is this:

if i subscribe 1 stream, and then send it 1 message and then exit the ldmsd_stream_publish and leave the store running, the zap layer keeps repeating the message to the stream delivery layer until the store daemon is stopped.

The *Really* odd thing is if i subscribe to 3 different streams and send a message to each of them (3 different ldmsd_stream_publish invocations), then the 1st named stream repeats forever as before, but streams 2 and 3 get the expected single message.

Arg! I have revised test scripts that demo this, sans the hello_cat.

**Comment by baallan** [comment]
> 
> 
> Arg indeed!
> Will need to see this live tomorrow, if I cannot get to test it today.
> I have done 2 streams and not gotten any of this (voltrino). Which sysstem are you on?

I'm testing on a rhel7 laptop, which network stack is much more like our clusters than voltrino.
I'm making a 2nd PR here with just the update to the test script to demo the 3-stream case.
I can clone the testing over to cts1x and verify the same problem happens there.

**Comment by baallan** [comment]
>     1. perhaps a verbose macro in the code is fine. I could see that multiple types of debugging could be unweildly. Do we do that anywhere else?

numerous places have a #ifdef xxxxx_DEBUG in the source. particularly around transport related issues where we don't want a performance hit from logging or even checking log level.
>
>     2. there is no stream unsubscribe. So it is the same as store_csv in that way.

There is a stream close, which seems to be the oddly named equivalent (well, maybe 'almost').

**Comment by baallan** [comment]
replaced by #2

**Pull request closed without merging**
