### PR TITLE
update stream_store test to ingest 3 streams

### PR DESCRIPTION
**Pull request by baallan**
streams bar, baz work ok,

### CODE REVIEW

**Comment by baallan** [comment]
@oceandlr these commits can be cherry-picked independently.

**Comment by oceandlr** [comment]
@baallan does the issue you see also occur with no store but with the hello plugin?

**Comment by baallan** [comment]
> 
> 
> @baallan does the issue you see also occur with no store but with the hello plugin?

I can reproduce this with the hello_sampler also.
I believe I've found the problem, in that extraneous prdcr_add provokes a loop in the stream delivery.
Oddly, an extraneous  prdcr_subscribe does Not provoke a loop in the stream delivery.
so the infinite delivery issue has been at least superficially resolved.

**Comment by oceandlr** [comment]
@baallan where is the "extraneous prdcr_add" ? Is this a configuration error in your script or something in the code?

**Comment by baallan** [comment]
> 
> 
> @baallan where is the "extraneous prdcr_add" ? Is this a configuration error in your script or something in the code?

in test script input file. revised the scripts here so they no longer provoke the loop.

**Comment by oceandlr** [comment]
I will take it that the store is correct and your script is now corrected. I don't know if the functionality you saw was intended -- it may be since there is a producer which was added and delivery is trying to occur. But that is orthogonal to this code request.

I will take a look at this tonight, so we can finish this off tomorrow.

**Comment by baallan** [comment]
There appears to still be a locking issue. debugging...

**Comment by baallan** [comment]
@oceandlr these three cherries have been updated per the discussion. I will send out the 'timestamp option' email and we should be able to come to some concensus tomorrow afternoon. Working on refactoring my remaining changes into separable patches.

**Comment by baallan** [comment]
@oceandlr I am now completely happy with my testing; everything gets cleaned up properly when the daemon exits, without races or deadlocks. The latest cherry in the list above is what accomplishes the proper unsubscribe (it has been revised from last nights).

Following the meeting discussion today, you should not take cherry "add timestamp config option to stream_csv store" and instead will enable something with an environment variable converted to an internal flag during config(). You might similarly skip 
"make debug statements conditionally compiled in successful delivery path" and wrap those debugs in the same flag.

**Comment by baallan** [comment]
@oceandlr let me know if you want to schedule something to walk through the happy patches list here.

**Pull request closed without merging**
